###
GET http://localhost:3001/eventos

###
# @name criarEvento
POST http://localhost:3001/eventos
Content-Type: application/json

{
    "nome": "Novo Evento",
    "data": "2017-01-01T00:00:00",
    "preco": 100,
    "descricao": "Este é um novo evento"
}

###
@eventoId = {{ criarEvento.response.body.id }}

###
GET http://localhost:3001/eventos/{{ eventoId }}

###
PATCH  http://localhost:3001/eventos/{{ eventoId }}
Content-Type: application/json

{
    "nome": "Novo Evento Editado",
    "data": "2017-01-01T00:00:00",
    "preco": 100,
    "descricao": "Este é um novo evento"
}

###
DELETE  http://localhost:3001/eventos/{{ eventoId }}

###
GET http://localhost:3001/eventos/{{ eventoId }}/lugares

###
# @name criarLugar
POST http://localhost:3001/eventos/{{ eventoId }}/lugares
Content-Type: application/json

{
    "nome": "A3"
}

###
@nomeLugar = {{ criarLugar.response.body.name }}

###
POST http://localhost:3001/eventos/{{ eventoId }}/reservar
Content-Type: application/json
X-Api-Token: 456

{
    "lugares": ["{{ nomeLugar }}"],
    "tipo_ingresso": "full",
    "email": "test@test.com"
}
    